#!/usr/bin/env python3

#This is lab2.py

import sys

def helloWorld():
	print('Hello World')
helloWorld()

if len(sys.argv) < 2:
        print('Please enter your name and age')
elif len(sys.argv) < 3:
        name = sys.argv[1]
        print('Please enter your age')
elif len(sys.argv) < 4:
        name = sys.argv[1]
        age = sys.argv[2]
        print(name)
        print(age)
        print('Hi NAME, you are AGE years old.')
        print('Hi ' + name + ', you are ' + age + ' years old.')                                                                  
